
export default {
    DRAWERTOGGLE : "DRAWERTOGGLE",
    ACTIVE_NAV_DRAWER_TOGGLER : "ACTIVE_NAV_DRAWER_TOGGLER",
    ACTIVE_NAV_DRAWER : "ACTIVE_NAV_DRAWER",
    CLICK_NAV_DRAWER_TOGGLER : "CLICK_NAV_DRAWER_TOGGLER",
    CLEAR_ACTIVE_DRAWER : "CLEAR_ACTIVE_DRAWER",
    FOCUS_BANK_INFO : "FOCUS_BANK_INFO",
    UNFOCUS_BANK_INFO : "UNFOCUS_BANK_INFO",

}