// import profileReducer from "../auth/auth.reducer";

export default {
    REGISTER_START:"REGISTER_START",
    REGISTER_SUCCESS:"REGISTER_SUCCESS",
    REGISTER_ERROR:"REGISTER_ERROR",

    LOGIN_START:"LOGIN_START",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_ERROR:"LOGIN_ERROR",

    CLEAR_STORAGE : 'CLEAR_STORAGE',
    SET_PHONENUMBER : "SET_PHONENUMBER",
    SET_PROFILE : "SET_PROFILE",
    GET_OTP : "GET_OTP"
}