export default {
    // GET_ESTATE_FAVORITE : "GET_ESTATE_START",
    // GET_ESTATE_SUCCESS : "GET_ESTATE_SUCCESS",
    // GET_ESTATE_ERROR : "GET_ESTATE_ERROR",

    IS_ESTATE_FAVORITE : "IS_ESTATE_FAVORITE",
}